# Generated by Django 2.2.7 on 2019-11-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('Name', models.TextField(max_length=255)),
                ('Price', models.FloatField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
